# SonarQube configuration
sonar.projectKey=trikifun:app
sonar.projectName=TrikiFun
sonar.projectVersion=1.0.0

# Path to source directories
sonar.sources=.
sonar.exclusions=node_modules/**,tests/**,coverage/**,**/*.test.js,eslint.config.js,monitoring/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Language specific options
sonar.javascript.environments=browser
sonar.javascript.globals=window,document
sonar.javascript.lcov.reportPaths=coverage/lcov.info
